### PR TITLE
Unify slf4j version

### PR DESCRIPTION
**Pull request by arso**
Signed-off-by: Artur Socha <asocha@redhat.com>

### CODE REVIEW

**Review by sandrobonazzola — APPROVED** [review]

**Comment by arso** [comment]
I have triggered  [copr build](https://copr.fedorainfracloud.org/coprs/ovirt/ovirt-master-snapshot/build/4415928/) on this branch and it failed as the [previous copr build](https://copr.fedorainfracloud.org/coprs/ovirt/ovirt-master-snapshot/build/4395979/)   on similar 'module filtering' error: 
```
 Problem: conflicting requests
  - package slf4j-jdk14-1.7.30-10.2.el8s.noarch is filtered out by modular filtering
```
previously:
```
Error: 
 Problem: package slf4j-jdk14-1.7.25-4.module_el8.5.0+922+9f7ad99e.noarch requires mvn(org.slf4j:slf4j-api) = 1.7.25, but none of the providers can be installed
  - cannot install both slf4j-1.7.28-3.module_el8.4.0+652+27abba4b.noarch and slf4j-1.7.25-4.module_el8.4.0+595+e59c9af2.noarch
  - cannot install both slf4j-1.7.25-4.module_el8.0.0+30+832da3a1.noarch and slf4j-1.7.28-3.module_el8.4.0+652+27abba4b.noarch
  - cannot install both slf4j-1.7.25-4.module_el8.5.0+922+9f7ad99e.noarch and slf4j-1.7.28-3.module_el8.4.0+652+27abba4b.noarch
  - cannot install the best candidate for the job
  - package slf4j-1.7.25-4.module_el8.0.0+39+6a9b6e22.noarch is filtered out by modular filtering
  - package slf4j-1.7.25-4.module_el8.6.0+1030+8d97e896.noarch is filtered out by modular filtering
```

**Comment by sandrobonazzola** [comment]
I'm trying to rebuild https://cbs.centos.org/koji/buildinfo?buildID=35276 in copr in order to make it available in the build root. Sadly I couldn't find a way to make an external repository listed as module hotfix for copr build root.

**Comment by sandrobonazzola** [comment]
> I'm trying to rebuild https://cbs.centos.org/koji/buildinfo?buildID=35276 in copr in order to make it available in the build root. Sadly I couldn't find a way to make an external repository listed as module hotfix for copr build root.

it fails with:
```
Error: Transaction test error:
  file /usr/share/java/org.eclipse.sisu.inject.jar from install of sisu-inject-1:0.3.3-6.module_el8.5.0+922+9f7ad99e.noarch conflicts with file from package sisu-0.3.4-2.module_el8.4.0+652+27abba4b.noarch
  file /usr/share/maven-poms/org.eclipse.sisu.inject.pom from install of sisu-inject-1:0.3.3-6.module_el8.5.0+922+9f7ad99e.noarch conflicts with file from package sisu-0.3.4-2.module_el8.4.0+652+27abba4b.noarch
  file /usr/share/java/org.eclipse.sisu.plexus.jar from install of sisu-plexus-1:0.3.3-6.module_el8.5.0+922+9f7ad99e.noarch conflicts with file from package sisu-0.3.4-2.module_el8.4.0+652+27abba4b.noarch
  file /usr/share/maven-poms/org.eclipse.sisu.plexus.pom from install of sisu-plexus-1:0.3.3-6.module_el8.5.0+922+9f7ad99e.noarch conflicts with file from package sisu-0.3.4-2.module_el8.4.0+652+27abba4b.noarch
  file /usr/share/java/maven-wagon/provider-api.jar from install of maven-wagon-provider-api-0:3.1.0-1.module_el8.5.0+922+9f7ad99e.noarch conflicts with file from package maven-wagon-3.3.4-2.module_el8.4.0+652+27abba4b.noarch
  file /usr/share/maven-poms/maven-wagon/provider-api.pom from install of maven-wagon-provider-api-0:3.1.0-1.module_el8.5.0+922+9f7ad99e.noarch conflicts with file from package maven-wagon-3.3.4-2.module_el8.4.0+652+27abba4b.noarch
```
so I guess we'll have to rebuild a few more packages.

**Comment by sandrobonazzola** [comment]
@mwperina any reason for not using slf4j-jdk14 from powertools here? Why did we need it rebuilt in CBS?

**Comment by mwperina** [comment]
Builds work fine on all COPR, CBS and brew so this patch is not needed at the moment

**Pull request closed without merging**
