### PR TITLE
Replace secret data with asterisks in debug logs

### PR DESCRIPTION
**Pull request by mz-pdm**
Vdsm provides secret data, namely TPM and secure boot NVRAM data, to Engine in response to getVmExternalData API call.  This data is returned with ‘_X_data’ key and occurs in debug logs.  When logging an API call response, let’s replace data of ‘_X_*’ keys with asterisks.

### CODE REVIEW

**Review by smelamud — APPROVED** [review]

**Comment by mz-pdm** [comment]
@mwperina , what to do with this, merge or abandon?

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
