### PR TITLE
Post 1.7.3 release

### PR DESCRIPTION
**Pull request by sandrobonazzola**

### CODE REVIEW

**Review by mwperina — COMMENTED** [review]
Should we bump the version to 1.7.4 in https://github.com/oVirt/vdsm-jsonrpc-java/blob/master/configure.ac#L24 ?

**Comment by sandrobonazzola** [comment]
> Should we bump the version to 1.7.4 in https://github.com/oVirt/vdsm-jsonrpc-java/blob/master/configure.ac#L24 ?

If we bump version we need to set release to 0. Right now the resulting build will look like `vdsm-jsonrpc-java-1.7.3-1.20231128143358.git71ab64b.el9.src.rpm` which is newer than the released one.

**Comment by sandrobonazzola** [comment]
pushed the bump, let's see how it looks like.

**Comment by sandrobonazzola** [comment]
Build now looks like `vdsm-jsonrpc-java-1.7.4-0.20231128145108.gitbdc6865.el8.src.rpm`

**Review by mwperina — APPROVED** [review]
LGTM

**Pull request merged**
